### ISSUE TITLE
codec can't decode byte 0x98 in position 6710

### ISSUE THREAD

**Issue by Aliaksandr3by** [FutureSharks/iptv-stream-cleaner#4]
Traceback (most recent call last):
  File "E:\Documents\IdeaProjects\iptv-stream-cleaner\stream-cleaner.py", line 233, in <module>
    filtered_playlist_items = filter_streams(args.input_file, args.timeout, args.blacklist_file)
  File "E:\Documents\IdeaProjects\iptv-stream-cleaner\stream-cleaner.py", line 197, in filter_streams
    content = f.readlines()
  File "C:\opt\Python39\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 6710: character maps to <undefined>

[ru.zip](https://github.com/FutureSharks/iptv-stream-cleaner/files/6918537/ru.zip)

![image](https://user-images.githubusercontent.com/11432724/127898920-04a48378-a52a-4657-9a7d-0402a1446a71.png)

**Comment by iHatePython** [comment]
4 years late but I ran into the same problem, turned out to be caused by python trying to open a file using the wrong encoding, in my case it used UTF-8 by default and it tried reading characters of undefined values.

What worked for me was editing "C:\opt\Python39\lib\encodings\cp1251.py" to add " errors='replace' " to every open command in that file (3 total), I saved the file and ran the command again and it seems to be working so far (it's a long list)
